# Payu configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
project: ol01
# Force payu to always find, and save, files in this scratch project directory
shortpath: /scratch/oz91

# Using payu sync is recommend to copy data from ephemeral scratch space to 
# longer term storage
sync:
  enable: false   # set path below and change to true
  path: ##/g/data/ik11/outputs/access-rom3-panan/MC_4km_jra_iaf+regionalpanan+isf         # Set to location on /g/data (e.g. /g/data/PROJECT/USER/EXPERIMENT)
  restart: false

  #Slow/cheaper layout
  #queue: normalsr
  #ncpus: 2990
  #jobfs: 10GB
  #mem: 14700GB

  #Expensive/fast layout
queue: normalsr
ncpus: 4992
jobfs: 10GB
mem: 24576GB

walltime: 5:00:00
jobname: iceshelfpanAn

model: access-om3

exe: access-om3-MOM6-CICE6

input:
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/kmt.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/ocean_hgrid.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/ocean_vgrid.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/ocean_temp_salt.res.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/salt_sfc_restore.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/salt_restore_mask.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/topog_seaice.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/topog.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/chl_globcolour_monthly_clim.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/access-om3-4km-ESMFmesh.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/access-om3-4km-nomask-ESMFmesh.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-rof-remap-weights.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-datm-ESMFmesh.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-drof-ESMFmesh.nc
        - /g/data/qv56/replicas/input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/landIce/
        - /g/data/qv56/replicas/input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/atmos/
        - /g/data/x77/cy8964/mom6/input/input-8km/ryf_gregorian_1975-1979_forcing_access_yr2_8km_fill.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/diag_rho2.nc
          # - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/ice_shelf_thick.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26COPY/ice_shelf_thick.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/bottom_roughness.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/tideamp.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/mask_table.2232.110x55
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/mask_table.1490.84x49
        - /g/data/x77/cy8964/mom6/input/input-8km/17.06.26/rofi_spread_Bgrid_non_advective.nc

collate:
  restart: true
  mpi: true
  walltime: 1:00:00
  mem: 190GB
  ncpus: 16
  queue: normal
  exe: mppnccombine-fast
runlog: true
metadata:
  enable: false

userscripts:
  archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh
  error: resub.sh
  run: rm -f resubmit.count

postscript: -v PROJECT,SCRIPTS_DIR=/g/data/vk83/apps/om3-scripts 
  -lstorage=${PBS_NCI_STORAGE}+gdata/xp65 
  /g/data/vk83/apps/om3-scripts/payu_config/postscript.sh

#Model software version
modules:
  use:
  - /g/data/vk83/prerelease/modules
  load:
  - model-tools/mppnccombine-fast/2025.07.000
  - nco/5.0.5
  - access-om3/pr189-18

payu_minimum_version: 1.1.6

platform:
  nodesize: 104
  nodemem: 512

restart_freq: 1YS
