# Payu configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
project: nm03
# Force payu to always find, and save, files in this scratch project directory
shortpath: /scratch/oz91

# Using payu sync is recommend to copy data from ephemeral scratch space to 
# longer term storage
sync:
  enable: true   # set path below and change to true
  path: /g/data/x77/cy8964/access-om3/archive/ice_shelf_panan-iaf_v2026_2_ssp585prescmr       # Set to location on /g/data (e.g. /g/data/PROJECT/USER/EXPERIMENT)
  restart: true

queue: normalsr
ncpus: 2990
jobfs: 10GB
mem: 14700GB

  #queue: normalsr
  #ncpus: 4992
  #jobfs: 10GB
  #mem: 24000GB

walltime: 4:00:00
jobname: prsspiaf8km_panAn_is

model: access-om3

exe: access-om3-MOM6-CICE6

input:
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/kmt.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/ocean_hgrid.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/ocean_vgrid.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/ocean_temp_salt.res.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/salt_sfc_restore.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/salt_restore_mask.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/topog_seaice.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/topog.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-ESMFmesh.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-nomask-ESMFmesh.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-rof-remap-weights.nc
        - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
        - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
        - /scratch/oz91/cy8964/replicas/input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/
        - /g/data/x77/cy8964/mom6/input/input-8km/ryf_gregorian_1995-1999_forcing_access_yr2_8km_fill.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/diag_rho2.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/ice_shelf_thick.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/bottom_roughness.nc
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/tideamp.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/mask_table.2232.110x55
        - /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/mask_table.1490.84x49
        - /g/data/x77/cy8964/mom6/input/input-8km/IAF_prescribed_melt_forcing_daily_resampled_1999.nc
        - /g/data/x77/cy8964/mom6/input/input-8km/grid_spec/

collate:
  restart: true
  mpi: true
  walltime: 1:00:00
  mem: 190GB
  ncpus: 16
  queue: normal
  exe: mppnccombine-fast
runlog: true
metadata:
  enable: false

userscripts:
  archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh
  error: resub.sh
  run: rm -f resubmit.count

postscript: -v PROJECT,SCRIPTS_DIR=/g/data/vk83/apps/om3-scripts 
  -lstorage=${PBS_NCI_STORAGE}+gdata/xp65 
  /g/data/vk83/apps/om3-scripts/payu_config/postscript.sh

#Model software version
modules:
  use:
  - /g/data/vk83/prerelease/modules
  load:
  - model-tools/mppnccombine-fast/2025.07.000
  - nco/5.0.5
  - access-om3/pr142-36

payu_minimum_version: 1.1.6

platform:
  nodesize: 104
  nodemem: 512

restart_freq: 1

