format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/tm70/cy8964/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-w4fxitax5qhwxig7stb6zlxc4ij3nkex/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 3f391d905a1db9c2fb3ef134b8c6163d
    md5: bb4e89d1a4a2cd4a8e68e8c576cd55ed
