format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-yssjuj2qlgevhm5wgesr6iln33kbpxua/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 89bdbf59b1166463076a49a2208f7ec4
    md5: 0760c99dcb6ce45a727ee592457f7f5e
